fixing podman vs docker

diff --git a/instructions/utilities/lab-build b/instructions/utilities/lab-build
--- a/instructions/utilities/lab-build
+++ b/instructions/utilities/lab-build
@@ -1,6 +1,17 @@
 #!/usr/bin/env bash
 #
 
+# Check if podman is available
+if command -v podman &> /dev/null; then
+    container_runtime="podman"
+# If podman is not available, check if docker is available
+elif command -v docker &> /dev/null; then
+    container_runtime="docker"
+else
+    echo "Error: Neither docker nor podman is installed. Exiting."
+    exit 1
+fi
+
 echo "Starting build process..."
 echo "Removing old site..."
 rm -rf ./www/*
@@ -8,7 +19,7 @@ rm -rf ./www/*
 echo "Building new site..."
 mkdir -p ./instructions/www
 
-podman run --rm --name showroom-builder \
+${container_runtime} run --rm --name showroom-builder \
     --platform linux/amd64 \
     -v "${PWD}:/antora" \
     docker.io/antora/antora default-site.yml
diff --git a/instructions/utilities/lab-serve b/instructions/utilities/lab-serve
--- a/instructions/utilities/lab-serve
+++ b/instructions/utilities/lab-serve
@@ -1,11 +1,23 @@
 #!/usr/bin/env bash
 #
 
+# Check if podman is available
+if command -v podman &> /dev/null; then
+    container_runtime="podman"
+# If podman is not available, check if docker is available
+elif command -v docker &> /dev/null; then
+    container_runtime="docker"
+else
+    echo "Error: Neither docker nor podman is installed. Exiting."
+    exit 1
+fi
+
+
 echo "Starting serve process..."
 # TODO: Add case statement to allow stopping, starting, and restarting
 # TODO: Add logic to detect both podman and docker, if both are installed, use podman as default "first found"
 # TODO: Move to RHEL image
-podman run -it --rm \
+${container_runtime} run -it --rm \
     --name showroom-httpd \
     -p 8443:80 \
     -v "${PWD}/instructions/www:/usr/local/apache2/htdocs/" \
